---
abstract: 'parsing CPANRatings data'
author:
  - 'Yo-An Lin <cornelius.howl {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-CPANRatings
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DateTime::Format::DateParse: 0
  HTML::TokeParser::Simple: 0
  JSON::XS: 0
  LWP::Simple: 0
  List::Util: 0
  Text::CSV_PP: 0
  URI: 0
  Web::Scraper: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
